version: 2.1
jobs:
  ut:
    machine: true
    steps:
      - checkout
      - run:
         name: Unit Test
<<<<<<< Updated upstream
         command: |
            make test
=======
         command: make test

>>>>>>> Stashed changes

workflows:
  version: 2
  any-commit:
    jobs:
      - ut
